"""empty message

Revision ID: 0d7f7d348293
Revises: 522c889f6bd1
Create Date: 2025-06-12 10:59:35.606128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7f7d348293'
down_revision = '522c889f6bd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zapatilla', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zapatilla', schema=None) as batch_op:
        batch_op.drop_column('stock')

    # ### end Alembic commands ###
