"""empty message

Revision ID: 468de642c468
Revises: ce8f464d3d29
Create Date: 2025-05-19 16:06:33.215296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '468de642c468'
down_revision = 'ce8f464d3d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
