"""empty message

Revision ID: 4f1cace7972f
Revises: c00011d8565c
Create Date: 2025-05-26 14:05:58.119460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1cace7972f'
down_revision = 'c00011d8565c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puntos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puntos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('puntos', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], name='puntos_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='puntos_pkey')
    )
    # ### end Alembic commands ###
