"""empty message

Revision ID: 521311d4ae31
Revises: 580a83c3b662
Create Date: 2025-05-15 19:41:10.312637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521311d4ae31'
down_revision = '580a83c3b662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oferta', sa.Boolean(), nullable=False))

    with op.batch_alter_table('zapatillas', schema=None) as batch_op:
        batch_op.drop_column('oferta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zapatillas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oferta', sa.BOOLEAN(), autoincrement=False, nullable=False))

    with op.batch_alter_table('modelos', schema=None) as batch_op:
        batch_op.drop_column('oferta')

    # ### end Alembic commands ###
