"""empty message

Revision ID: 522c889f6bd1
Revises: 3e81ca92ea7d
Create Date: 2025-06-04 08:09:34.320056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522c889f6bd1'
down_revision = '3e81ca92ea7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('img')

    # ### end Alembic commands ###
