"""initial

Revision ID: 580a83c3b662
Revises: 
Create Date: 2025-05-14 16:34:59.934949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580a83c3b662'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marcas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('modelos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zapatillas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=False),
    sa.Column('tallas', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('oferta', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('zapatillas_id', sa.Integer(), nullable=False),
    sa.Column('talla', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['zapatillas_id'], ['zapatillas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_column('lastName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastName', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    op.drop_table('carrito')
    op.drop_table('zapatillas')
    op.drop_table('modelos')
    op.drop_table('marcas')
    # ### end Alembic commands ###
