"""empty message

Revision ID: 60433bf9c009
Revises: 468de642c468
Create Date: 2025-05-19 16:08:01.518476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60433bf9c009'
down_revision = '468de642c468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.drop_column('img')

    # ### end Alembic commands ###
