"""empty message

Revision ID: 675272f88a73
Revises: c710cb19acb0
Create Date: 2025-05-26 12:38:03.657702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675272f88a73'
down_revision = 'c710cb19acb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
