"""empty message

Revision ID: 840d3cb89add
Revises: b30d8af18293
Create Date: 2025-05-26 14:10:38.275254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840d3cb89add'
down_revision = 'b30d8af18293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrito_zapatilla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrito_id', sa.Integer(), nullable=False),
    sa.Column('zapatilla_id', sa.Integer(), nullable=False),
    sa.Column('talla', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carrito_id'], ['carrito.id'], ),
    sa.ForeignKeyConstraint(['zapatilla_id'], ['zapatilla.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('carritozapatilla')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carritozapatilla',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('carrito_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('zapatilla_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('talla', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['carrito_id'], ['carrito.id'], name='carritozapatilla_carrito_id_fkey'),
    sa.ForeignKeyConstraint(['zapatilla_id'], ['zapatilla.id'], name='carritozapatilla_zapatilla_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='carritozapatilla_pkey')
    )
    op.drop_table('carrito_zapatilla')
    # ### end Alembic commands ###
