"""empty message

Revision ID: aedd659ee44d
Revises: 0d7f7d348293
Create Date: 2025-06-17 20:13:48.366218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aedd659ee44d'
down_revision = '0d7f7d348293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('talla_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zapatilla_id', sa.Integer(), nullable=False),
    sa.Column('talla', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['zapatilla_id'], ['zapatilla.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zapatilla', schema=None) as batch_op:
        batch_op.drop_column('tallas')
        batch_op.drop_column('stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zapatilla', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tallas', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))

    op.drop_table('talla_stock')
    # ### end Alembic commands ###
