"""empty message

Revision ID: c3b6cb57def3
Revises: 1e390c378bc9
Create Date: 2025-05-16 10:33:13.609116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3b6cb57def3'
down_revision = '1e390c378bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrito_zapatilla',
    sa.Column('talla', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('zapatilla_id', sa.Integer(), nullable=False),
    sa.Column('carrito_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carrito_id'], ['carrito.id'], ),
    sa.ForeignKeyConstraint(['zapatilla_id'], ['zapatilla.id'], ),
    sa.PrimaryKeyConstraint('zapatilla_id', 'carrito_id')
    )
    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.drop_constraint('carrito_zapatilla_id_fkey', type_='foreignkey')
        batch_op.drop_column('cantidad')
        batch_op.drop_column('talla')
        batch_op.drop_column('zapatilla_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zapatilla_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('talla', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('carrito_zapatilla_id_fkey', 'zapatilla', ['zapatilla_id'], ['id'])

    op.drop_table('carrito_zapatilla')
    # ### end Alembic commands ###
