"""empty message

Revision ID: c710cb19acb0
Revises: d388294834f7
Create Date: 2025-05-26 12:36:18.219398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c710cb19acb0'
down_revision = 'd388294834f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrito_zapatilla', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True, nullable=False))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrito_zapatilla', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
