"""empty message

Revision ID: ce8f464d3d29
Revises: c3b6cb57def3
Create Date: 2025-05-16 10:57:11.040794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8f464d3d29'
down_revision = 'c3b6cb57def3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zapatilla', schema=None) as batch_op:
        batch_op.drop_constraint('zapatilla_marca_id_fkey', type_='foreignkey')
        batch_op.drop_column('marca_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zapatilla', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('zapatilla_marca_id_fkey', 'marca', ['marca_id'], ['id'])

    # ### end Alembic commands ###
