"""empty message

Revision ID: d388294834f7
Revises: 9061e5e63d65
Create Date: 2025-05-24 13:52:02.387984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd388294834f7'
down_revision = '9061e5e63d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrito_zapatilla', schema=None) as batch_op:
        batch_op.alter_column('talla',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cantidad',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrito_zapatilla', schema=None) as batch_op:
        batch_op.alter_column('cantidad',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('talla',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
